esphome:
  name: gaspetronas
  friendly_name: gaspetronas

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rnKlvnosEMnXOVsKiNAGnP3D/4dR5P3fqM7Mu7ErWlE="

ota:
  password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gaspetronas Fallback Hotspot"
    password: !secret wifi_password



captive_portal:

dallas:
  - pin: GPIO14


sensor:
  # RAW Scale input
  - platform: hx711
    name: "Gas Petronas Raw"
    id: gas_petronas_raw
    dout_pin: GPIO4
    clk_pin: GPIO5
    gain: 128
    update_interval: 10s # ishak 0.2
    filters:
      - calibrate_linear:
          - -3727 -> 0.06
          - 601223 -> 18.45
 #         - 949870 -> 30.43
      - sliding_window_moving_average:
          window_size: 50
          send_every: 10
          send_first_at: 10
    unit_of_measurement: kg
    accuracy_decimals: 1

  - platform: copy 
    name: Petronas Berat Gas kg
    source_id: gas_petronas_raw
    id: petronas_berat_gas_kg
    state_class: measurement 
    unit_of_measurement: 'kg' 
    accuracy_decimals: 1
    filters: 
      - calibrate_linear:
          - 14 -> 16.5
          - 30.6 -> 0.01

  - platform: template
    name: "Petronas Gas Usage (m³)"
    id: petronas_gas_usage_m3
    unit_of_measurement: 'm³'
    icon: mdi:meter-gas-outline
    state_class: total_increasing
    device_class: gas
    accuracy_decimals: 1
    lambda: return id(petronas_berat_gas_kg).state / 0.8;
    update_interval: 10 s

  - platform: dallas
    address: 0xd63c00e381418228
    name: "Dapur Kiri"
    id: dapur_kiri
    accuracy_decimals: 2

  - platform: dallas
    address: 0xf83c3fe381e49a28
    name: "Dapur Kanan"
    id: dapur_kanan
    accuracy_decimals: 2

binary_sensor:
  - platform: template
    name: "Status Dapur Kiri"
    lambda: |-
      if (id(dapur_kiri).state > 37) {
        // Garage Door is open.
        return true;
      } else {
        // Garage Door is closed.
        return false;
      }  

  - platform: template
    name: "Status Dapur Kanan"
    lambda: |-
      if (id(dapur_kanan).state > 37) {
        // Garage Door is open.
        return true;
      } else {
        // Garage Door is closed.
        return false;
      }  

web_server:
  port: 80
